var products =[
    
    {
        id: 1,
        img:'/images/products/oso_estilo_pelota.png',
        name: 'OSO ESTILO PELOTA',
        categoty:'Apapacho oficial', 
        tematic: '', 
        material: 'poliester', 
        weight: 20,
        height: 20,
        price: 30000,
        rating: 4,

    },
    {
        id: 2,
        img:'/images/products/conejo_rosa_feliz.png',
        name: 'CONEJO ROSA FELIZ',
        categoty: 'Apapacho oficial',
        tematic: '',
        material: 'poliester',
        weight: 20,
        height: 35,
        price: 36000,
        rating: 4,

    },
    {
        id: 3,
        img:'/images/products/pinguino_azul_cariñoso.png',
        name: 'PINGUINO AZUL CARIÑOSO',
        categoty: 'Apapacho oficial', 
        tematic: '', 
        material: 'poliester',
        weight: 20,
        height: 30,
        price: 38000,
        rating: 5,

    },
    {
        id: 4,
        img:'/images/products/pooh.png',
        name: 'POOH',
        categoty: 'Disney',
        tematic: '', 
        material: 'felpa',
        weight: 20,
        height: 20,
        price: 38000,
        rating: 3,

    },
    {
        id: 5,
        img:'/images/products/dinosaurio_rosa_feliz.png',
        name: 'DINOSAURIO ROSA FELIZ',
        categoty: 'Apapacho oficial', 
        tematic: '',
        material: 'poliester', 
        weight: 20,
        height: 35,
        price: 40000,
        rating: 4,

    },
    {
        id: 6,
        img:'/images/products/stitch.png',
        name: 'STITCH',
        categoty: 'Disney',
        tematic: '',
        material: 'poliester', 
        weight: 20,
        height: 25,
        price: 42000,
        rating: 5,

    },
    {
        id: 7,
        img:'/images/products/mickey_mouse.png',
        name: 'MICKEY MOUSE',
        categoty: 'Disney',
        tematic: '', 
        material: 'poliester', 
        weight: 30,
        height: 40,
        price: 48000,
        rating: 4,

    },
    {
        id: 8,
        img:'/images/products/minnie_mouse.png',
        name: 'MINNIE MOUSE',
        categoty: 'Disney',
        tematic: '', 
        material: 'poliester', 
        weight: 30,
        height: 40,
        price: 50000,
        rating: 4,

    },
    {
        id: 9,
        img:'/images/products/cerdo_super_man.png',
        name: 'CERDO SUPER MAN',
        categoty: 'Apapacho oficial', 
        tematic: 'Halloween',
        material: 'poliester',
        weight: 20,
        height: 25,
        price: 32000,
        rating: 3,

    },
    {
        id: 10,
        img:'/images/products/canguro_tierno.png',
        name: 'CANGURO TIERNO',
        categoty: 'Apapacho oficial', 
        tematic: '', 
        material: 'poliester', 
        weight: 20,
        height: 25,
        price: 32000,
        rating: 3,

    },
    {
        id: 11,
        img:'/images/products/unicornio_acostado.png',
        name: 'UNICORNIO ACOSTADO',
        categoty: 'Apapacho oficial', 
        tematic: '', 
        material: 'poliester',
        weight: 40,
        height: 20,
        price: 36000,
        rating: 4,

    },

    {
        id: 12,
        img:'/images/products/oso_super_man.png',
        name: 'OSO SUPER MAN',
        categoty: 'Apapacho oficial', 
        tematic: 'Halloween',
        material: 'felpa',
        weight: 20,
        height: 50,
        price: 56000,
        rating: 3,

    },
    {
        id: 13,
        img:'/images/products/perro_calabaza.png',
        name: 'PERRO CALABAZA',
        categoty: 'Apapacho oficial', 
        tematic: 'Halloween',
        material: 'poliester', 
        weight: 50,
        height: 30,
        price: 48000,
        rating: 4,

    },
    {
        id: 14,
        img:'/images/products/oso_rosa_corazon.png',
        name: 'OSO ROSA CORAZÓN',
        categoty: 'Apapacho oficial', 
        tematic: 'San valantine', 
        material: 'felpa',
        weight: 30,
        height: 40,
        price: 47000,
        rating: 2,

    },
    {
        id: 15,
        img:'/images/products/foca_caramelo_azul.png',
        name: 'FOCA CARAMELO AZUL',
        categoty: 'Apapacho oficial', 
        tematic: 'San valantine',
        material: 'poliester', 
        weight: 20,
        height: 30,
        price: 35000,
        rating: 3,

    },
    {
        id: 16,
        img:'/images/products/oso_batman.png',
        name: 'OSO BATMAN',
        categoty: 'Apapacho oficial', 
        tematic: 'Halloween',
        material: 'felpa',
        weight: 20,
        height: 40,
        price: 39000,
        rating: 4,

    },
    {
        id: 17,
        img:'/images/products/cerdo_mujer_maravilla.png',
        name: 'CERDO MUJER MARAVILLA',
        categoty: 'Apapacho oficial',
        tematic: 'Halloween',
        material: 'poliester',
        weight: 20,
        height: 25,
        price: 32000,
        rating: 3,

    },
    {
        id: 18,
        img:'/images/products/rainbowdash_baby.png',
        name: 'RAINBOWDASH BABY',
        categoty: 'My little ponny', 
        tematic: '',
        material: 'poliester', 
        weight: 25,
        height: 40,
        price: 48000,
        rating: 4,

    },
    {
        id: 19,
        img:'/images/products/oso_love.png',
        name: 'OSO LOVE',
        categoty: 'Apapacho oficial', 
        tematic: '',
        material: 'poliester', 
        weight: 40,
        height: 60,
        price: 89000,
        rating: 4,

    },
    {
        id: 20,
        img:'/images/products/pareja_perritos_enamorados.png',
        name: 'PAREJA DE PERRITOS ENAMORADOS',
        categoty: 'Apapacho oficial', 
        tematic: 'San valantine', 
        material: 'poliester', 
        weight: 25,
        height: 40,
        price: 80000,
        rating: 4,
    },
    {
        id: 21,
        img:'/images/products/pareja_up.png',
        name: 'PAREJA UP',
        categoty: 'Pixar',
        tematic: 'San valantine', 
        material: 'poliester',
        weight: 30,
        height: 40,
        price: 90000,
        rating: 5,

    },
    {
        id: 22,
        img:'/images/products/oso_corazon_rojo_acuadros.png',
        name: 'OSO CORAZÓN ROJO A CUADROS',
        categoty: 'Apapacho oficial', 
        tematic: 'San valantine', 
        material: 'poliester',
        weight: 30,
        height: 40,
        price: 46000,
        rating: 3,

    },
    {
        id: 23,
        img:'/images/products/oso_blanco_love.png',        
        name: 'OSO BLANCO LOVE ',
        categoty: 'Apapacho oficial', 
        tematic:  'San valantine', 
        material: 'felpa',
        weight: 20,
        height: 30,
        price: 42000,
        rating: 3,

    },
    {
        id: 24,
        img:'/images/products/rainbowdash.png',
        name: 'RAINBOW DASH',
        categoty: 'My little ponny', 
        tematic: '',
        material: 'poliester', 
        weight: 35,
        height: 40,
        price: 56000,
        rating: 4,

    },
    {
        id: 25,
        img:'/images/products/FLUTTERSHY.png',
        name: 'FLUTTERSHY',
        categoty: 'My little ponny', 
        tematic: '', 
        material: 'poliester', 
        weight: 35,
        height: 40,
        price: 54000,
        rating: 3,

    },
    {
        id: 26,
        img:'/images/products/rabia_intensamente.png',        
        name: 'RABIA INTENSAMENTE',
        categoty: 'Pixar',
        tematic: '',
        material: 'poliester',
        weight: 20,
        height: 20,
        price: 32000,
        rating: 4,

    },
    {
        id: 27,
        img:'/images/products/buuoody.png',        
        name: 'BUUOODY',
        categoty: 'Pixar', 
        tematic: '', 
        material: 'poliester',
        weight: 20,
        height: 20,
        price: 42000,
        rating: 3,

    },
    {
        id: 28,
        img:'/images/products/nemo.png',        
        name: 'NEMO',
        categoty: 'Disney', 
        tematic: '', 
        material: 'poliester', 
        weight: 30,
        height: 20,
        price: 48000,
        rating: 4,

    },
    {
        id: 29,
        img:'/images/products/oso_amarillo_cariñoso.png',        
        name: 'OSO AMARILLO CARIÑOSO',
        categoty: 'Apapacho oficial',
        tematic: 'San valantine',
        material: 'poliester', 
        weight: 20,
        height: 40,
        price: 42000,
        rating: 3,

    },
    {
        id: 30,
        img:'/images/products/cocodrilo_sonriente.png',        
        name: 'COCODRILO SONRIENTE',
        categoty: 'Apapacho oficial',
        tematic: '', 
        material: 'poliester', 
        weight: 25,
        height: 40,
        price: 48000,
        rating: 4,

    },
    {
        id: 31,
        img:'/images/products/nala.png',        
        name: 'NALA',
        categoty: 'Disney', 
        tematic: 'San valantine',
        material: 'poliester',
        weight: 40,
        height: 30,
        price: 48000,
        rating: 4,

    },
    {
        id: 32,
        img:'/images/products/pony_princesa.png',        
        name: 'PONY RAINBOW PRINCESA',
        categoty: 'My little ponny', 
        tematic: '',
        material: 'poliester', 
        weight: 40,
        height: 30,
        price: 52000,
        rating: 4,

    },
    {
        id: 33,
        img:'/images/products/olaf_frozen.png',        
        name: 'OLAF FROZEN',
        categoty: 'Disney',
        tematic: '', 
        material: 'poliester',
        weight: 20,
        height: 40,
        price: 56000,
        rating: 3,

    },
    {
        id: 34,
        img:'/images/products/simba.png',        
        name: 'SIMBA',
        categoty: 'Disney',
        tematic: 'San valantine',
        material: 'poliester',
        weight: 40,
        height: 30,
        price: 48000,
        rating: 4,

    },
    {
        id: 35,
        img:'/images/products/oso_te_amo.png',        
        name: 'OSO TE AMO',
        categoty: 'Apapacho oficial', 
        tematic: 'San valantine',
        material: 'poliester',
        weight: 20,
        height: 20,
        price: 32000,
        rating: 2,

    },
    {
        id: 36,
        img:'/images/products/solivan.png',        
        name: 'SOLIVAN',
        categoty: 'Pixar',
        tematic: '', 
        material: 'felpa',
        weight: 40,
        height: 40,
        price: 80000,
        rating: 5,

    },

    

];
module.exports = products;